name: rlcache
channels:
  - conda-forge
dependencies:
 - python
 - numpy
 - docopt
 - urllib3
 - jupyter
 - pydot
 - graphviz
 - tensorflow-gpu
 - libiconv
 - uwsgi
 - pip:
   - sklearn
   - watermark
   - jupyter_tensorboard
   - rlgraph
   - matplotlib
   - faker
   - flask
   - prometheus_client